version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/serve1090"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/packages/pump1090"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/packages/piTemp"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/packages/dump1090"
    schedule:
      interval: "daily"